name: Build mdk4 IPK for K2P

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download OpenWrt 25.12.4 SDK
        run: |
          set -e

          SDK_URL="https://downloads.openwrt.org/releases/25.12.4/targets/ramips/mt7621/"
          SDK_FILE="openwrt-sdk-25.12.4-ramips-mt7621_gcc-14.3.0_musl.Linux-x86_64.tar.zst"

          echo "Downloading:"
          echo "$SDK_URL$SDK_FILE"

          curl -fL "$SDK_URL$SDK_FILE" -o sdk.tar.zst

      - name: Extract SDK
        run: |
          set -e

          mkdir sdk

          tar --zstd -xf sdk.tar.zst \
            -C sdk \
            --strip-components=1

          rm sdk.tar.zst

      - name: Install feeds
        working-directory: sdk
        run: |
          set -e

          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Copy mdk4 package
        run: |
          set -e

          mkdir -p sdk/package/mdk4
          cp package/mdk4/Makefile sdk/package/mdk4/Makefile

          echo "===== MDK4 MAKEFILE ====="
          nl -ba sdk/package/mdk4/Makefile

      - name: Configure SDK
        working-directory: sdk
        run: |
          set -e
          make defconfig

      - name: Build mdk4
        working-directory: sdk
        run: |
          set -e
          make package/mdk4/compile V=s

      - name: Find IPK
        run: |
          echo "===== GENERATED IPK ====="
          find sdk/bin/packages -type f -name 'mdk4_*.ipk' -print

      - name: Upload IPK
        uses: actions/upload-artifact@v4
        with:
          name: mdk4-ipk-k2p-openwrt-25.12.4
          path: sdk/bin/packages/**/mdk4_*.ipk
          path: sdk/bin/packages/**/mdk4_*.ipk
