name: Build mdk4 for Phicomm K2P

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build OpenWrt Package using Official SDK Action
        uses: openwrt/gh-action-sdk@main
        with:
          arch: ramips_mt7621
          package: mdk4
